[package]
authors = ["Antti Ker√§nen <detegr@gmail.com>"]
name = "lanistatsit-backend"
version = "0.1.0"

[dependencies]
rustc-serialize = "0.3.19"
rustful = "0.9.0"
rand = "0.3"
clippy = { version = "*", optional = true }

[features]
default = ["clippy"]
